<?php

namespace AppBundle\Repository;

/**
 * EarningsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EarningsRepository extends \Doctrine\ORM\EntityRepository
{
}
