<?php

namespace AppBundle\Repository;

/**
 * SpendingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpendingRepository extends \Doctrine\ORM\EntityRepository
{
}
