app_entry:
    resource: "@AppBundle/Resources/config/routing/entry.yml"
    prefix:   /entry

app_user:
        resource: "@AppBundle/Resources/config/routing/user.yml"
        prefix:   /user

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
