AppBundle\Entity\Spending:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SpendingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        label:
            type: string
            length: 255
            unique: false
        amount:
            type: integer
        isFixed:
            type: boolean
            column: is_fixed

            #ajouter relation manyToOne (many spending to one user) ou manToMany (many spending to many user?)
    lifecycleCallbacks: {  }
