AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        pseudo:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
